{
 "title": "HTTP/S LB Backend Services",
 "tags": [
  "Networking",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   },
   {
    "name": "backend",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Backend Request Count by Code Class",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name",
       "metric.label.response_code_class"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "query": "",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Request Count by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name",
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "mqlQuery": {
      "aliasBy": "",
      "expression": "fetch https_lb_rule::loadbalancing.googleapis.com/https/backend_request_count\n| { t_0:\n      filter metric.response_code_class = 500\n      | align delta()\n      | group_by [resource.backend_target_name],\n          [value_backend_request_count_aggregate:\n             aggregate(value.backend_request_count)]\n  ; t_1:\n      ident\n      | align delta()\n      | group_by [resource.backend_target_name],\n          [value_backend_request_count_aggregate:\n             aggregate(value.backend_request_count)] }\n| outer_join [0]\n| value\n    [t_0_value_backend_request_count_aggregate_div:\n       div(t_0.value_backend_request_count_aggregate,\n         t_1.value_backend_request_count_aggregate)]",
      "projectName": "$project",
      "query": "fetch https_lb_rule::loadbalancing.googleapis.com/https/backend_request_count\n| { t_0:\n      filter metric.response_code_class = 500\n      | align delta()\n      | group_by [resource.backend_target_name],\n          [value_backend_request_count_aggregate:\n             aggregate(value.backend_request_count)]\n  ; t_1:\n      ident\n      | align delta()\n      | group_by [resource.backend_target_name],\n          [value_backend_request_count_aggregate:\n             aggregate(value.backend_request_count)] }\n| outer_join [0]\n| value\n    [t_0_value_backend_request_count_aggregate_div:\n       div(t_0.value_backend_request_count_aggregate,\n         t_1.value_backend_request_count_aggregate)]"
     }
    }
   ]
  },
  {
   "title": "Error Count by Path and Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "mqlQuery": {
      "aliasBy": "",
      "expression": "fetch https_lb_rule::loadbalancing.googleapis.com/https/backend_request_count\n| filter metric.response_code_class = 500\n| align delta()\n| group_by\n    [resource.matched_url_path_rule, resource.backend_target_name,\n     metric.response_code],\n    [value_backend_request_count_aggregate:\n       aggregate(value.backend_request_count)]",
      "projectName": "$project",
      "query": "fetch https_lb_rule::loadbalancing.googleapis.com/https/backend_request_count\n| filter metric.response_code_class = 500\n| align delta()\n| group_by\n    [resource.matched_url_path_rule, resource.backend_target_name,\n     metric.response_code],\n    [value_backend_request_count_aggregate:\n       aggregate(value.backend_request_count)]"
     }
    }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend P50 Latency by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name",
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_latencies",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "$project",
      "unit": "ms",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Backend Request Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Request Bytes by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name",
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_request_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Response Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_response_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Backend Response Bytes by Path",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.type",
       "=",
       "https_lb_rule",
       "AND",
       "resource.label.backend_target_name",
       "=",
       "$backend"
      ],
      "groupBys": [
       "resource.label.url_map_name",
       "resource.label.backend_target_name",
       "resource.label.matched_url_path_rule"
      ],
      "metricKind": "DELTA",
      "metricType": "loadbalancing.googleapis.com/https/backend_response_bytes_count",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}